# Generated by Django 5.2.8 on 2025-12-02 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnsku', models.CharField(blank=True, max_length=100, verbose_name='FNSKU')),
                ('upc', models.CharField(blank=True, max_length=100, verbose_name='UPC')),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('created_by', models.CharField(max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(editable=False, max_length=64, verbose_name='校验码')),
            ],
            options={
                'verbose_name': '标签版本',
                'verbose_name_plural': '标签版本',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=100, unique=True, verbose_name='商品SKU')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='商品名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=100, unique=True, verbose_name='批次号')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('verified', '已复核'), ('shipped', '已发货'), ('rejected', '已拒收')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.labelversion', verbose_name='绑定的标签版本')),
            ],
        ),
        migrations.AddField(
            model_name='labelversion',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.sku', verbose_name='关联SKU'),
        ),
        migrations.AlterUniqueTogether(
            name='labelversion',
            unique_together={('sku', 'version_number')},
        ),
    ]
