# Generated by Django 5.2.8 on 2025-12-02 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='labelversion',
            options={},
        ),
        migrations.AddField(
            model_name='shipmentbatch',
            name='reviewer1_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipmentbatch',
            name='reviewer1_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentbatch',
            name='reviewer1_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipmentbatch',
            name='reviewer2_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipmentbatch',
            name='reviewer2_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentbatch',
            name='reviewer2_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labelversion',
            name='checksum',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='labelversion',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='labelversion',
            name='fnsku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='labelversion',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.sku'),
        ),
        migrations.AlterField(
            model_name='labelversion',
            name='upc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='labelversion',
            name='version_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipmentbatch',
            name='batch_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shipmentbatch',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.labelversion'),
        ),
        migrations.AlterField(
            model_name='shipmentbatch',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipmentbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sku',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='shipmentbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to='warehouse.operator'),
        ),
        migrations.AddField(
            model_name='shipmentbatch',
            name='reviewer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_batches_1', to='warehouse.operator', verbose_name='First Reviewer'),
        ),
        migrations.AddField(
            model_name='shipmentbatch',
            name='reviewer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_batches_2', to='warehouse.operator', verbose_name='Second Reviewer'),
        ),
    ]
