# Generated by Django 5.2.8 on 2025-12-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_operator_alter_labelversion_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Location Code"
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("receiving", "Receiving Area"),
                            ("storage", "Storage Area"),
                            ("picking", "Picking Area"),
                            ("shipping", "Shipping Area"),
                        ],
                        default="storage",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="InboundReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_no", models.CharField(max_length=100, unique=True)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, help_text="External PO number", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.operator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutboundExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("picking", "Picking"),
                            ("packed", "Packed"),
                            ("shipped", "Shipped"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution",
                        to="warehouse.shipmentbatch",
                    ),
                ),
                (
                    "picker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.operator",
                        verbose_name="Picker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound Receipt"),
                            ("outbound", "Outbound Shipment"),
                            ("adjust", "Inventory Adjustment"),
                            ("move", "Location Move"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_change", models.IntegerField()),
                ("balance_after", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("reference_document", models.CharField(blank=True, max_length=100)),
                (
                    "label_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.labelversion",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.operator",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="warehouse.sku"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.warehouselocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InboundLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_declared",
                    models.PositiveIntegerField(
                        default=0, help_text="Quantity expected"
                    ),
                ),
                (
                    "quantity_received",
                    models.PositiveIntegerField(
                        default=0, help_text="Actual quantity scanned"
                    ),
                ),
                ("scanned_hash", models.CharField(blank=True, max_length=64)),
                (
                    "label_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.labelversion",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.inboundreceipt",
                    ),
                ),
                (
                    "target_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.warehouselocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.labelversion",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.warehouselocation",
                    ),
                ),
            ],
            options={
                "unique_together": {("location", "label_version")},
            },
        ),
    ]
